.github/setup-apt.sh
.github/workflows/build.yaml
scripts/testsuite-filter

This PR tests the newly added pipeline

Add ci jobs for make-report and make-report multilib

---

scripts/aggregate.py
scripts/compare_testsuite_log.py

This PR addresses an issue found in #41. Duplicate multilib/non-multilib testsuite results were being de-duplicated. This PR eliminates that de-duplication so we're always aware of all the builds that are performed. It also adds type hints to some files.

Emit duplicates and label multilib results

---

scripts/aggregate.py

- Changed order of summary from resolved->unresolved->new to new->resolved->unresolved
- can now distinguish between same targets under different libc

Added linux/newlib label to summary

---

.github/actions/download-comparison-artifacts/action.yaml
.github/workflows/generate-summary.yaml

We can drastically reduce the amount of repetition in generate-summary by using composite actions. This will make it easier to add new targets in the future.

Use composite actions

---

.github/actions/download-comparison-artifacts/action.yaml
scripts/download_artifacts.py
scripts/download_single_artifact.py

Reduced API calls from 400 -> 30

limit api call usage

---

.github/workflows/build-frequent.yaml
.github/workflows/dockerfile
.github/workflows/generate-summary.yaml
.github/workflows/regression-runner.yaml

Tested on newlib, currently testing on linux. This increases the stage2 artifact sizes, so we may want to trim them down in the future if possible. Just kicking off the PR test build now and will revisit in a future PR to optimize.

Fix testing config

---

scripts/aggregate.py
scripts/bisect.sh
scripts/single_testsuite.py

- Same code as #195 just fixing git history
- Add basic git bisect script to use in git bisect run <script> for automating bisections locally. Eventually will want to incorporate into ci pipeline once we figure out timeout issues
- Updated single testsuite script so that it finds the exp file instead of having the user pass in the exp file manually
- Adjusted aggregate.py to print new errors before resolved errors

Bisect and finding testsuite take 2

---

.github/workflows/generate-summary.yaml

Uninstall and reinstall pip to fix ssl crypto issue

Upgrade pyopenssl and cryptography

---

.github/actions/download-all-comparison-artifacts/action.yaml
.github/workflows/build-frequent.yaml
.github/workflows/generate-summary.yaml
scripts/scrape_issue_info.py

- Moved downloading artifacts for all targets to composite action
- Updated workflow dispatch to include another input for bisection hash

basic autoregenerate bisected issues using workflow dispatch

---

.github/workflows/build-frequent.yaml

Should help reduce congestion (especially with all the timeouts).

Remove x86 build

---

.github/actions/download-all-comparison-artifacts/action.yaml
.github/actions/download-comparison-artifacts/action.yaml
.github/workflows/build-frequent.yaml
.github/workflows/generate-summary.yaml
scripts/aggregate.py
scripts/compare_all_artifacts.py
scripts/download_artifacts.py

- separate download and compare. 
- update aggregate summary info

Refactor download script 

---

scripts/compare_testsuite_log.py

Numbers should match output of the testsuite filter

remove failure de-duplication

---

.github/workflows/build-frequent.yaml
.github/workflows/build-weekly.yaml

Complete the migration to https://github.com/patrick-rivos/gcc-postcommit-ci

Turn off scheduled runs

---

scripts/aggregate.py

Tested with summary logs from https://github.com/patrick-rivos/gcc-postcommit-ci/actions/runs/6445977945 and https://github.com/patrick-rivos/gcc-postcommit-ci/actions/runs/6476442019

update to report multilib values in issue

---

scripts/download_artifacts.py

Update artifact list

---

scripts/generate_apply_report.py

Add links to current and existing baseline

---

Makefile.in

`--with-tune` actually sets target board tune

add tune option to gen target boards

---

scripts/aggregate.py

This'll let us emit titles that don't match the precommit's pattern matching

Add title prefix to allow users to overwrite issue name

---

scripts/check_patch_checks.py
scripts/create_patches_files.py

add support for creating patches from list of files

---

test/allowlist/gcc/glibc.log
test/allowlist/gcc/glibc.rv32.zbs.log

double check naming scheme for the bitmanip hello failure

add flakey failures to allowlist

---

scripts/generate_linter_fail_report.py

fix url mismatch

---

test/allowlist/gcc/newlib.v.log

https://github.com/patrick-rivos/gcc-postcommit-ci/issues/402

add flakey newlib timeout failures

---

Makefile.in

Enable llvm asserts by default

---

.gitignore

Make consistent with upstream
glibc: 2.37 --> 2.39
binutils: 2.41 --> 2.42
gdb: 12.1 --> 14.1
llvm: 16.0.5 --> 17.0.2

bump submodules

---

scripts/compare_glibc_log.py
scripts/testsuite-filter

Split up into a series for easier review.

Add support for glibc .sum file parsing

---

Makefile.in
README.md
configure
configure.ac
scripts/compare_testsuite_log.py
scripts/generate_target_board
scripts/separate_multilib_results.py
scripts/testsuite-filter

Compared postcommit run https://github.com/patrick-rivos/gcc-postcommit-ci/issues/864 with local run of same hash with no differences

Update makefile to allow passing in additional parameters

---

scripts/create_patches_files.py

Tested locally using https://patchwork.sourceware.org/api/1.3/patches/?order=date&project=6&since=2024-06-03T03:00:00&before=2024-06-03T03:15:00
I recommend viewing the 2 commits separately instead of looking at the overall diff.

Add pagination support to precommit

---

scripts/generate_apply_report.py

Pass in baseline/tip-of-tree hash into wrapper

---

scripts/parse_new_build_warnings.py
test/pytests/test_scripts/test_parse_new_build_warnings.py

1. Modify the script to add additional function that compares all the files between the old directory and the new directory
2. Create pytest for the script to prevent potential failures while edit

parse_new_warnings.py changes

---

scripts/download_artifacts.py

This resolves issues like this:
https://github.com/patrick-rivos/gcc-postcommit-ci/actions/runs/9555148075/job/26337723557#step:7:84

Update download-artifact callsites

---

scripts/compare_all_artifacts.py
scripts/compare_testsuite_log.py

Removed argparse choices since it will allow any prefix now

use prefix to get links and update coordination branch links

---

scripts/aggregate.py

Also remove allowlist.txt since I couldn't find any usage of it

Add assert preventing blank summary issues

---

scripts/aggregate.py

the unresolved failures will be put into a different comment due to character limitations

save interesting unresolved failures

---

scripts/create_patches_files.py
scripts/parse_new_build_warnings.py
test/pytests/test_scripts/test_create_patches_files.py

Fetch and grep the mbox file rather than the title. This will allow people to cc patchworks-ci@rivosinc.com or mention riscv/risc-v anywhere in their patch for the ci to run.

Precommit mbox grep
