patrick-rivos/riscv-gnu-toolchain

scripts/compare-testsuite-log

**Summary**
compare-testsuite-log python script compares two testsuite-filter script output logs and creates github issue markdown file as an output. 
5 arguments are:
- -phash, --previous-hash: hash of the previous commit
- -plog, --previous-log: path to the previous commit testsuite result log
- -chash, --current-hash: hash of the current commit
- -clog, --current-log: path to the current commit testsuite result log
- -o, --output-markdown: path for the output markdown file
**Example Output**
---
title: j4dad5->fe43de
assignees: ('patrick-rivos', 'kevinl-rivos')
labels: bug
---
|Resolved Failures|gcc|g++|gfortran|
|---|---|---|---|
|rv32imacdf ilp32 medlow|0/0|2/2|0/0|
|rv32imac ilp32 medlow|1/1|2/2|2/2|
|Unresolved Failures|gcc|g++|gfortran|
|---|---|---|---|
|rv32imac ilp32 …

Create testsuite log compare script for CI

---

.github/workflows/build-frequent.yaml
.github/workflows/summary-runner.yaml
scripts/aggregate.py
scripts/compare_testsuite_log.py
scripts/download_artifacts.py
scripts/get-most-recent-ci-hash.py
scripts/get_most_recent_ci_hash.py

- The `download_artifacts.py` script checks the repo for existing artifacts and will download all testsuite artifacts associated with the provided hash (specified with -hash input) and the previous successful hash. Failures are logged in the `./logs/` directory where:
-  `./logs/failed_build.txt` contains the names of artifacts without `-report.log` in the file name and cannot be found for the specified hash
- `./logs/failed_testsuite.txt` contains the names of artifacts with `-report.log` in the file name and cannot be found for the specified hash
- `./logs/no_baseline.txt` contains the names of artifacts with `-report.log` in the file name but a previous successful hash cannot be found to compare against
- `aggregate.py` parses through all summaries output by `compare-testsuite-log.py` …

Aggregate results

---

.github/workflows/generate-summary.yaml
.github/workflows/regression-runner.yaml

Currently all summaries will fail to find a baseline. Cloning GCC before attempting to download artifacts will fix this.

Clone GCC before attempting to find artifacts

---

.github/workflows/generate-summary.yaml
scripts/aggregate.py
scripts/compare_testsuite_log.py
scripts/download_artifacts.py

Updates:
- Fixed missing hashes under `Previous Hashes` column in issue summary
- Update current workflow artifact download to use `actions/download-artifact@v3` for all supported file logs and binaries (if the logs didn't exist)

Fix artifact download

---

.github/workflows/build-frequent.yaml

Adds the ability to run a single target from the github CI. Useful when bisecting failures, but generates issues that look like they have build failures for the un-run targets.

Add single target runner

---

.github/workflows/build-frequent.yaml
.github/workflows/generate-summary.yaml
.github/workflows/regression-runner.yaml
scripts/download_artifacts.py

Adds vector and bitmanip. Vector crypto needs to wait till the Binutils 2.41 release this coming Sunday (7/30).

Add more targets and refactor multilib targets

---

.github/workflows/generate-summary.yaml

Add the associated ci run to the summary and add warning that issue has been trimmed if output exceeds 100+ lines

Update issue summary

---

.github/workflows/generate-summary.yaml

This automatically associates new issues with the trunk-regressions project _if_ they were made by a scheduled run.
This is hard to test without duplicating the project, but since this step runs last it will likely not impact anything even if it doesn't work.

Associate scheduled runs with trunk-regressions project automatically

---

.github/workflows/build-frequent.yaml
.github/workflows/generate-summary.yaml
.github/workflows/regression-runner.yaml
scripts/download_artifacts.py

We haven't seen any failures from musl specifically, so this patch removes it so we can add more newlib/linux targets like vector crypto.

Add vector crypto and remove musl builds

---

test/allowlist/gcc/common.log
test/allowlist/gcc/glibc.ilp32.log
test/allowlist/gcc/glibc.log
test/allowlist/gcc/glibc.lp64.log
test/allowlist/gcc/glibc.rv32.f.log
test/allowlist/gcc/glibc.rv32.log
test/allowlist/gcc/lp64.log
test/allowlist/gcc/newlib-nano.f.log
test/allowlist/gcc/newlib-nano.log
test/allowlist/gcc/newlib.log
test/allowlist/gcc/rv64.log

This reverts commit 4add4792e6abe4da0aa0ea774b67d524ce23479e.
We currently get some esoteric errors that other people aren't testing for. We should eventually resolve the allowlist's failures, but this should reduce the amount of esoteric regressions we encounter.

Revert "Remove gcc allowlist"

---

.github/workflows/generate-summary.yaml

Most (all?) github actions work with classic projects. We'll need to go through the github API to implement this functionality. Leaving the conditional execution and a placeholder to avoid having to figure out that again.

Replace project action with dummy code any mark as TODO

---

.github/workflows/build-frequent.yaml
.github/workflows/generate-summary.yaml
.github/workflows/regression-runner.yaml
scripts/aggregate.py
scripts/download_artifacts.py

This adds the [RV23U64 profile](https://github.com/riscv/riscv-profiles/blob/main/rva23-profile.adoc) and introduces nicknames for configs with long isa strings.

Add RV23A profile

---

.github/workflows/regression-runner.yaml
scripts/download_artifacts.py

Testsuite failures were being incorrectly labeled as build failures. This patch fixes that.

Fix binary zip name

---

.github/workflows/generate-summary.yaml
scripts/download_artifacts.py

[get_most_recent_ci_hash.py](https://github.com/patrick-rivos/riscv-gnu-toolchain/blob/build-frequent/scripts/get_most_recent_ci_hash.py) was encountering an error where it could not retrieve the 100 most recent commits due to an error with the tree. Pull the most updated version of gcc in the regenerate summary to fix
Test: https://github.com/ewlu/riscv-gnu-toolchain/actions/runs/6006001115/job/16307721347?pr=41
Regenerate: https://github.com/patrick-rivos/riscv-gnu-toolchain/actions/runs/6017124614

Fix bisection regenerated issue no-baseline error when baseline exists

---

.github/dockerfile/configure.sh
.github/workflows/regression-runner.yaml

This will allow us to sidestep stubs.h failures.

Build singlelib targets with multilib-generator

---

.github/workflows/build-frequent.yaml

Corresponds with this line in the other repo: https://github.com/patrick-rivos/gcc-postcommit-ci/blob/main/.github/workflows/run-frequent.yaml#L13

Change cadence to twice a day to allow other repo to get started

---

scripts/separate_multilib_results.py

separates report log output into files each containing the information for one target to be used in the comparison function

add multilib report log separator script

---

scripts/post_check_to_patchworks.py

This allows us to error out rather than silently failing when we forget to filter.

Force user to provide github event name

---

scripts/get_previous_timestamp.py

Originally just used the previous scheduled workflow. With adding issue closer script, those timestamps were also considered which occasionally would miss patches

filter out any scheduled actions other than patchwork workflows

---

scripts/march-to-cpu-opt

version commit: https://github.com/qemu/qemu/commit/f48c205fb42be48e2e47b7e1cd9a2802e5ca17b0
`Zve*` being deprecated in favor of `zve*` and same for `Zfh*`

bump qemu to v8.2.0 for vector crypto support and add ext opt to march-to-cpu-opt

---

scripts/download_artifacts.py

All runners use `download_artifacts.py` to pull the previous log artifacts. `download_artifacts.py` assumes no prefixes which results in never finding a previous logs for weekly runners since all weekly runner artifacts are prefixed.

fix weekly runner comparisons 

---

scripts/download_artifacts.py

`download_artifacts.py` label which builds fail by checking if the build artifact exists https://github.com/patrick-rivos/riscv-gnu-toolchain/blob/build-frequent/scripts/download_artifacts.py#L138-L144. The previous implementation generated the minimal subset of possible arch combinations. Adding weekly build arch extensions in 3fdf1f389f682f49db66dea1675abdc35917d1ca caused false `build-failure` labels to be generated since it would not be able to find the weekly build arches when `prefix == ''`. Separating the possible arch extensions into different branches should allow the regular daily runs to be `build-failure` free (unless a real build failure occurs).

have separate branches for weekly run possible names

---

scripts/create_patches_files.py

Issue can be seen here: https://patchwork.sourceware.org/project/gcc/list/?series=33832
We didn't apply the first patch since it's not RISC-V.
Split into a series for easier review.

Pull non-riscv precommit dependencies

---

scripts/download_artifacts.py

prefixing coordination runners so that precommit doesn't use those as baseline

add suppport for frequent coordination branch runners

---

scripts/get_staging_hash.py

Coordination branches have titles "Coordination Branch Testsuite Status <HASH>" which passes the title check. Remove them from consideration through the labels.

prevent coordination branch hashes from being chosen

---

scripts/parse_new_warning.py

This script is originally created to run in pre-commit time to check if the new patches have introduced new warnings compared to the baseline.
It takes in two stderr.log and construct a set of newly introduced warnings.
Then the warnings are exported to a given output file.

Create new warning parse script that compares two stderr.log

---

scripts/generate_linter_fail_report.py

Since the linter is upstream people can submit patches against it directly.

Remove contact info from linter fail report.

---

scripts/generate_apply_report.py

This adds a section to the precommit apply step that looks like this:
git log --oneline from the most recently applied patch to the baseline
```
> git log --oneline 1588983be61^..HEAD
89349e6a099 Cleanup whitespace in target-supports.exp
1588983be61 RISC-V: Add Zalrsc amo-op patterns
```

Produce a git log after applying the patches

---

scripts/generate_apply_report.py

The gcc tree is in the applied-to-tip-of-tree state when this script is run. We need to collect the git log files before this is script is run and select the relevant one when this is run.

Generate seperate log files and select at runtime

---

scripts/download_artifact.py

Shutil.move has a bug in python3.8 where using path as a parameter doesn't resolve the path correctly. Instead of directly passing path as an argument, pass string

Modify download_artifact.py for possible break in python 3.8

---

.github/workflows/pre-pull-request.yaml
scripts/download_artifacts.py
scripts/get_baseline_hash.py
test/pytests/conftest.py
test/pytests/test_scripts/test_download_artifacts.py

After the discussion with @patrick-rivos and @ewlu, downloading the build log artifacts feature is decided to reside in download_artifacts.py. 
1. download_artifacts.py now first searches for the report artifact to determine the correct base hash for the given target template. Then the base hash could be used to download other artifacts
2. --build-logs option enables the build log artifact download. --build-logs-dir option is used to pass the build logs artifact destination. If it's not specified while --build-logs is enabled, it defaults to previous_build_logs directory.
3. Pytest for download_build_logs_artifact function is added to check a proper download. conftest.py is created to take github token as input since github api call is required for this test. If the github token is not …

Build log download feature for download_artifacts
